# Generated by Django 3.2.19 on 2023-07-02 17:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None, verbose_name='Phone number')),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
