# Generated by Django 3.2.19 on 2023-07-04 17:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('meter_vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metervendor',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number'),
        ),
    ]
