# Generated by Django 3.2.19 on 2023-07-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_vendors', '0002_alter_metervendor_phone_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metervendor',
            options={'ordering': ('name',)},
        ),
    ]
