# Generated by Django 4.0 on 2022-10-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.CharField(max_length=255)),
                ('charges', models.CharField(max_length=255)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('meter_no', models.CharField(max_length=11)),
                ('token_no', models.CharField(max_length=255, unique=True)),
                ('num_of_units', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
