# Generated by Django 4.0 on 2022-10-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_amount_paid_alter_payment_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='num_of_units',
            field=models.PositiveIntegerField(),
        ),
    ]
