# Generated by Django 4.0 on 2022-11-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='meter_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='num_of_units',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='token_no',
        ),
    ]
