# Generated by Django 3.2.19 on 2023-08-25 16:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20230820_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer_phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+256709645302', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
