# Generated by Django 4.0 on 2022-11-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Email will be used for resetting your password', max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DefaultMeterManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.OneToOneField(limit_choices_to={'account_type': 4}, on_delete=django.db.models.deletion.RESTRICT, to='users.user')),
            ],
        ),
    ]
