# Generated by Django 3.2.19 on 2023-07-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='account_type',
            field=models.PositiveIntegerField(choices=[(0, 'Django Admin'), (1, 'Super Admin'), (2, 'Admin'), (4, 'Manager'), (8, 'Default Manager')], default=4),
        ),
    ]
