# Generated by Django 4.0 on 2022-10-01 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_charge', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('fixed_charge', models.PositiveIntegerField()),
                ('label', models.CharField(help_text='Keep it precise ie: HomeCharges', max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Meter categories',
            },
        ),
    ]
