# Generated by Django 4.1 on 2022-09-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metercategory',
            options={'verbose_name_plural': 'Meter categories'},
        ),
    ]
