# Generated by Django 4.1 on 2022-09-06 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.CharField(max_length=255)),
                ('charges_ugx', models.CharField(max_length=255)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.CharField(max_length=255, unique=True)),
                ('num_of_units', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meter.meter')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.payment')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
