# Generated by Django 4.1 on 2022-09-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='meter_no',
            field=models.CharField(default='11111111111', max_length=11),
        ),
        migrations.AddField(
            model_name='payment',
            name='num_of_units',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
