# Generated by Django 4.1 on 2022-09-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_charges_ugx_payment_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='token_no',
            field=models.CharField(default='1020192924829489', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='meter_no',
            field=models.CharField(max_length=11),
        ),
    ]
