# Generated by Django 4.1 on 2022-09-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_payment_charges_ugx_payment_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='token_no',
            field=models.CharField(max_length=255),
        ),
    ]
