# Generated by Django 4.0 on 2022-10-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telephone_contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
