# Generated by Django 4.0 on 2022-10-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '__first__'),
        ('meter_categories', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_no', models.CharField(max_length=11, unique=True, verbose_name='Meter number')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='meter_categories.metercategory')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'account_type': 4}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='users.user')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='manufacturers.metermanufacturer')),
            ],
            options={
                'ordering': ['manager'],
            },
        ),
    ]
