# Generated by Django 3.2.19 on 2023-07-02 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meter_vendors', '0001_initial'),
        ('meters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('account_type', 4), ('account_type', 8), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meter',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='meter_vendors.metervendor'),
        ),
    ]
