# Generated by Django 3.2.19 on 2023-07-04 14:56

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models
import django.db.models.deletion
import users.managers

User = get_user_model()
default_manager = User.objects.get_default_manager()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='manager',
            field=models.ForeignKey(blank=True, default=default_manager.id, limit_choices_to=models.Q(('account_type', 4), ('account_type', 8), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meters', to=settings.AUTH_USER_MODEL),
        ),
    ]
