# Generated by Django 3.2.19 on 2023-08-14 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meter_vendors', '0003_alter_metervendor_options'),
        ('meters', '0007_alter_meter_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ['meter_number']},
        ),
        migrations.AddField(
            model_name='meter',
            name='previous_vendor_registrations',
            field=models.ManyToManyField(related_name='registered_meters', to='meter_vendors.MeterVendor'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='manager',
            field=models.ForeignKey(default=users.managers.UserManager.get_default_manager, limit_choices_to=models.Q(('account_type', 4), ('account_type', 8), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='meters', to=settings.AUTH_USER_MODEL),
        ),
    ]
