# Generated by Django 4.0 on 2022-11-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meters', '0001_initial'),
        ('payments', '0005_remove_payment_meter_no_remove_payment_num_of_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.CharField(max_length=255, unique=True)),
                ('num_of_units', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='meters.meter')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='payments.payment')),
            ],
        ),
    ]
