# Generated by Django 3.2.19 on 2023-07-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge_tokens', '0002_rechargetokenorder_placed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargetokenorder',
            name='token_no',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
