# Generated by Django 3.2.19 on 2023-07-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge_tokens', '0003_alter_rechargetokenorder_token_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargetokenorder',
            name='token_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
