# Generated by Django 3.2.19 on 2023-07-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge_tokens', '0004_alter_rechargetokenorder_token_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargetokenorder',
            name='recharge_amount',
            field=models.PositiveIntegerField(default=30000),
            preserve_default=False,
        ),
    ]
