# Generated by Django 3.2.19 on 2023-07-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recharge_tokens', '0005_rechargetokenorder_recharge_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rechargetokenorder',
            options={'ordering': ('-placed_at',)},
        ),
        migrations.RemoveField(
            model_name='rechargetokenorder',
            name='placed_by',
        ),
    ]
