# Generated by Django 2.2.24 on 2022-03-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidmeteruser',
            name='acc_type',
            field=models.PositiveIntegerField(choices=[(1, 'Super Admin'), (2, 'Admin'), (4, 'Manager')], default=4),
        ),
    ]
