# Generated by Django 2.2.24 on 2022-03-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220329_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidmeteruser',
            name='acc_type',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Super Admin'), (2, 'Admin'), (4, 'Manager')]),
        ),
    ]
