import environ

env = environ.Env()

PAYLEO_TESTING = env.bool("PAYLEO_TESTING")
PAYLEO_MERCHANT_CODE = env.str("PAYLEO_MERCHANT_CODE")
PAYLEO_CONSUMER_KEY = env.str("PAYLEO_CONSUMER_KEY")
PAYLEO_CONSUMER_SECRET = env.str("PAYLEO_CONSUMER_SECRET")



