import environ

env = environ.Env()

PAYLEO_MERCHANT_CODE = env.str("PAYLEO_MERCHANT_CODE")
PAYLEO_CONSUMER_KEY = env.str("PAYLEO_CONSUMER_KEY")
PAYLEO_CONSUMER_SECRET = env.str("PAYLEO_CONSUMER_SECRET")
PAYLEO_CALLBACK_IP = env.str("PAYLEO_CALLBACK_IP")
PAYLEO_MIN_TRANSACTION_AMOUNT = 500
PAYLEO_CLIENT_TRANSACTION_ID_LENGTH = 15

