# Generated by Django 3.0.2 on 2022-07-29 07:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Manufacturer's Name")),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_no', models.CharField(max_length=11, unique=True, verbose_name='Meter Number')),
            ],
        ),
        migrations.CreateModel(
            name='MeterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_charge', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('fixed_charge', models.PositiveIntegerField()),
                ('label', models.CharField(help_text='Keep it precise ie: HomeCharges', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name="Purchaser's Name")),
                ('token_no', models.CharField(max_length=255, unique=True)),
                ('amount_paid', models.CharField(max_length=255)),
                ('num_of_units', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meter.Meter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meter.MeterCategory'),
        ),
        migrations.AddField(
            model_name='meter',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'account_type': 4}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meter',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meter.Manufacturer'),
        ),
    ]
