# Generated by Django 3.0.2 on 2022-07-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
