# Generated by Django 4.1 on 2022-09-11 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter_category', '0002_alter_metercategory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meter_manufacturer', '0001_initial'),
        ('meter', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='meter_category.metercategory'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 4}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meter',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='meter_manufacturer.metermanufacturer'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_no',
            field=models.CharField(max_length=11, unique=True, verbose_name='Meter number'),
        ),
    ]
