# Generated by Django 2.2.24 on 2022-03-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_auto_20220329_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_no',
            field=models.CharField(max_length=11, unique=True, verbose_name='Meter Number'),
        ),
    ]
