# Generated by Django 3.0.2 on 2022-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_meter_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenlog',
            name='name',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(default='Kabalagala', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='telephone_contact',
            field=models.CharField(default='0702289811', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
